---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[zoneminder::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
    driver_config:
        network:
            - ["private_network", {ip: "10.0.3.240"}]
